- name: create EventFlow Operator deployment
  k8s_extensions_v1beta1_deployment:
   name: operator
   namespace: '{{ namespace }}'
   labels:
     app: eventflow
     service: operator
   replicas: 1
   spec_template_metadata_labels:
     app: eventflow
     service: operator
   containers:
   - env:
     image: docker.io/streamzi/eventflow-operator:latest
     imagePullPolicy: IfNotPresent
     name: operator
